# Generated by Django 3.2.3 on 2021-05-24 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WebAdress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_adress', models.URLField()),
                ('site_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VisitCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('job', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('photo', models.URLField(blank=True)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('surname', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('Cu', 'customer'), ('Co', 'company'), ('Em', 'employee')], default='customer', max_length=2)),
                ('adress', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='customer.adress')),
            ],
        ),
        migrations.CreateModel(
            name='PersonnalWebAdress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('visit_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.visitcard')),
                ('web_adress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.webadress')),
            ],
        ),
    ]
