# Generated by Django 3.2.3 on 2021-06-01 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitcard',
            name='adress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.adress'),
        ),
        migrations.AlterField(
            model_name='visitcard',
            name='status',
            field=models.CharField(choices=[('Cu', 'customer'), ('Co', 'company'), ('Em', 'employee'), ('Ad', 'admin')], default='customer', max_length=2),
        ),
    ]
