# Generated by Django 3.2.3 on 2021-05-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('off_the_shelf_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('production_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('stock', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_unit', models.CharField(max_length=25)),
            ],
        ),
    ]
