# Generated by Django 3.2.3 on 2021-06-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.TextField(default='default_name', max_length=255),
            preserve_default=False,
        ),
    ]
